---
- name: Add macOS POSIX permissions of '{{ homebrew_prefix }}/*' for the group '{{ homebrew_group }}'.
  file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    mode: "{{ homebrew_posix_permissions }}"
    owner: "{{ homebrew_user if (homebrew_user is defined and homebrew_user | length > 0) else omit }}"
    group: "{{ homebrew_group | mandatory }}"
    recurse: yes
    state: directory
  register: posix_permissions
  loop: "{{ homebrew_folders_base + homebrew_folders_additional }}"
